-- Procedure to drop foreign key constraints
CREATE OR REPLACE PROCEDURE drop_foreign_key_constraints IS
    v_constraint_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_constraint_exists
    FROM user_constraints
    WHERE constraint_name IN (
        'FK_PRESCRIPTION_CUSTOMER_ID',
        'FK_PRESCRIBED_DRUGS_PRESCRIPTION_ID',
        'FK_EMPLOYEE_ROLE_ID',
        'FK_ORDER_BILL_EMPLOYEE_ID',
        'FK_ORDER_BILL_PRESCRIPTION_ID',
        'FK_ORDERED_DRUGS_DRUG_ID',
        'FK_PAYMENT_BILL_ORDER_ID',
        'FK_PAYMENT_BILL_CUSTOMER_ID',
        'FK_ORDERED_DRUGS_ORDER_ID',
        'FK_NOTIFICATION_DRUG_ID',
        'FK_EMPLOYEE_NOTIFICATION_EMP_ID',
        'FK_EMPLOYEE_NOTIFICATION_NOTIF_ID'
    );

    IF v_constraint_exists > 0 THEN
        -- Drop foreign key constraints using dynamic SQL
        EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION DROP CONSTRAINT FK_PRESCRIPTION_CUSTOMER_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIBED_DRUGS DROP CONSTRAINT FK_PRESCRIBED_DRUGS_PRESCRIPTION_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_ROLE_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE ORDER_BILL DROP CONSTRAINT FK_ORDER_BILL_EMPLOYEE_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE ORDER_BILL DROP CONSTRAINT FK_ORDER_BILL_PRESCRIPTION_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_BILL DROP CONSTRAINT FK_PAYMENT_BILL_ORDER_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_BILL DROP CONSTRAINT FK_PAYMENT_BILL_CUSTOMER_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE ORDERED_DRUGS DROP CONSTRAINT FK_ORDERED_DRUGS_DRUG_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE ORDERED_DRUGS DROP CONSTRAINT FK_ORDERED_DRUGS_ORDER_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE NOTIFICATION DROP CONSTRAINT FK_NOTIFICATION_DRUG_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEE_NOTIFICATION DROP CONSTRAINT FK_EMPLOYEE_NOTIFICATION_EMP_ID';
        EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEE_NOTIFICATION DROP CONSTRAINT FK_EMPLOYEE_NOTIFICATION_NOTIF_ID';
    END IF;
END drop_foreign_key_constraints;
/

-- Procedure to drop all tables
CREATE OR REPLACE PROCEDURE drop_all_tables IS
    v_table_count NUMBER;
BEGIN
    -- Check if tables exist
    SELECT COUNT(*)
    INTO v_table_count
    FROM user_tables
    WHERE table_name IN (
        'CUSTOMER',
        'PRESCRIPTION',
        'PRESCRIBED_DRUGS',
        'ORDER_BILL',
        'PAYMENT_BILL',
        'ORDERED_DRUGS',
        'INVENTORY',
        'NOTIFICATION',
        'EMPLOYEE_NOTIFICATION',
        'EMPLOYEE',
        'ROLE'
    );

    -- Drop tables if they exist
    IF v_table_count > 0 THEN
        FOR tab IN (SELECT table_name FROM user_tables WHERE table_name IN (
            'INSURANCE',
            'CUSTOMER',
            'PRESCRIPTION',
            'PRESCRIBED_DRUGS',
            'ORDER_BILL',
            'PAYMENT_BILL',
            'ORDERED_DRUGS',
            'INVENTORY',
            'NOTIFICATION',
            'EMPLOYEE_NOTIFICATION',
            'EMPLOYEE',
            'ROLE'
        )) LOOP
            EXECUTE IMMEDIATE 'DROP TABLE ' || tab.table_name;
        END LOOP;
    END IF;
END drop_all_tables;
/


EXEC drop_foreign_key_constraints;
EXEC drop_all_tables;